##################################################
# ElasticSearch PersistentVolume
##################################################  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: test 
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /usr/share/elasticsearch/data/
