##################################################
# ElasticSearch Service
##################################################  
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: rest
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: inter-node
    protocol: TCP
    port: 9300
    targetPort: 9300
  type: ClusterIP
