##################################################
# ElasticSearch Statefulset
##################################################  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 3
  serviceName: elasticsearch
  selector:
    matchLabels:
        app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command:
            - sh
            - '-c'
            - sysctl
            - '-p'
          imagePullPolicy: Always
        - name: increase-fd-ulimit
          image: busybox
          command:
            - sh
            - '-c'
            - ulimit -n 65536
      hostname: elasticsearch
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "2G"
            cpu: "1"             
        ports:
          - name: rest
            containerPort: 9200
            protocol: TCP
          - name: inter-node
            containerPort: 9300
            protocol: TCP
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: >-
              elasticsearch-0.elasticsearch,elasticsearch.elasticsearch,elasticsearch.elasticsearch
          - name: cluster.initial_master_nodes
            value: 'elasticsearch-0,elasticsearch-1,elasticsearch-2'
          - name: ES_JAVA_OPTS
            value: '-Xms1024m -Xmx1568m'
          - name: xpack.security.enabled
            value: 'false'
          - name: TZ
            value: Europe/Istanbul
        volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: elasticsearch-data
        namespace: test
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-storage
        volumeMode: Filesystem
